### ISSUE TITLE
Failing tests do not fail the task

### ISSUE THREAD

**Issue by alihacks** [jsforce/gulp-jsforce-deploy#5]
Is there a way to fail the task if one or many unit tests fail? Currently I get:

Success: true
Done: true
Number Component Errors; 0
Number Components Deployed: 0
Number Components Total: 0
Number Test Errors; 33
Number Tests Completed: 133
Number Tests Total: 166
....
[17:54:19] Finished 'runtests' after 33 s

**Comment by stomita** [comment]
Passing `rollbackOnError` option will fail the deployment when there are any error test results.
