### ISSUE TITLE
No package.xml found

### ISSUE THREAD

**Issue by weivreca** [jsforce/gulp-jsforce-deploy#7]
Hi,
I've got the following file structure for my package (see attached zip):
├── pkg
│   ├── package.xml
│   └── staticresources
│       ├── test.resource
│       └── test.resource-meta.xml

It seems to zip fine, I can log into Salesforce but I get the error below. I tried it with a deploy package that I successfully deployed with Ant but got the same error. Any help would be really appreciated. Thanks

Dave
[deploy.zip](https://github.com/jsforce/gulp-jsforce-deploy/files/321594/deploy.zip)

[14:29:12] Failures:
[14:29:12]  - Error on pages/package.xml : No package.xml found
[14:29:12] 'deploy' errored after 8.48 s
[14:29:12] Error: Deploy Failed.
    at C:\HaoIDE\TestDBYo\node_modules\gulp-jsforce-deploy\index.js:21:27
    at tryCallOne (C:\HaoIDE\TestDBYo\node_modules\promise\lib\core.js:37:12)
    at C:\HaoIDE\TestDBYo\node_modules\promise\lib\core.js:123:15
    at flush (C:\HaoIDE\TestDBYo\node_modules\asap\raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

**Comment by stomita** [comment]
You need to zip the package content to a certain directory. Your zip content resides in root.

Your attached zip file (fails)

```
$ unzip -vl deploy.zip
Archive:  deploy.zip
 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
     235  Defl:N      160  32%  06-18-16 14:13  b0152697  package.xml
       0  Stored        0   0%  06-18-16 14:02  00000000  staticresources/
   66029  Defl:N    65458   1%  06-18-16 13:59  10a64bd7  staticresources/test.resource
     221  Defl:N      160  28%  06-18-16 14:02  d303224c  staticresources/test.resource-meta.xml
--------          -------  ---                            -------
   66485            65778   1%                            4 files
```

The correct zip file

```
$ unzip -vl pkg.zip
Archive:  pkg.zip
 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
       0  Stored        0   0%  06-18-16 15:16  00000000  pkg/
     235  Defl:N      160  32%  06-18-16 14:13  b0152697  pkg/package.xml
       0  Stored        0   0%  06-18-16 14:02  00000000  pkg/staticresources/
   66029  Defl:N    65439   1%  06-18-16 13:59  10a64bd7  pkg/staticresources/test.resource
     221  Defl:N      160  28%  06-18-16 14:02  d303224c  pkg/staticresources/test.resource-meta.xml
--------          -------  ---                            -------
   66485            65759   1%                            5 files
```

**Comment by weivreca** [comment]
Fantastic. Thanks for the help and quick reply

**Comment by Kunal-Deshpande** [comment]
Hi,

You can use the directory structure that you specified in the question.
But you have to set the deploy option `{ singlePackage : true }`
